- name : deploy latest package 
  hosts : PROD
  become : yes
  vars :
    USERNAME : tom_user
    DIR : /tom
    TOM_PATH : /tom/apache-tomcat-9.0.70/webapps
    WAR_PACK : /tom/apache-tomcat-9.0.70/webapps/ks.war
    WAR_URL : http://192.168.29.17:8081/repository/maven-snapshots/com/ksapp/ks/7-SNAPSHOT/ks-7-20221222.011259-5.war

  tasks :
    - name : Create User for Tomcat
      ansible.builtin.user:
        name: "{{USERNAME}}"

    - name: Creates directory
      file:
        path: "{{DIR}}"
        state: directory
        owner: "{{USERNAME}}"
        group: "{{USERNAME}}"
        mode: 0775

    - name: Extract tom.tar into /tom
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
        dest: "{{DIR}}"
        remote_src : yes
      become_user : "{{USERNAME}}"

    - name : Install java on remote node
      yum :
        name : java
        state : latest

    - name: remove files and directories
      file:
        state: "{{item}}"
        path: "{{TOM_PATH}}"
        owner: "{{USERNAME}}"
        group: "{{USERNAME}}"
      with_items:
        - absent
        - directory
        
    - name : deploy war 
      get_url:
        url : "{{WAR_URL}}"
        dest : "{{WAR_PACK}}"
        
   
        






  