- name : deploy latest package 
  hosts : PROD
  become : yes
  vars :
    USERNAME : tom_user

  tasks :
    - name : Create User for Tomcat
      ansible.builtin.user:
        name: "{{USERNAME}}"

    - name: Creates directory
      file:
        path: /tom
        state: directory
        owner: "{{USERNAME}}"
        group: "{{USERNAME}}"
        mode: 0775